### PR TITLE
out of date with node-postgres

### PR DESCRIPTION
**Pull request by jrf0110**
node-postgres has been bumped up to version 3.x because of some non-backwards compatible changes, see [here](https://github.com/brianc/node-postgres/blob/a29affe17e5ec1eba4844afa231eeb5ffefb0a61/NEWS.md)

I don't think that these will impact on this project, so can the [package.json peer](https://github.com/goodybag/node-pg-transaction/blob/master/package.json#L10) be updated to "3.x" ?

### CODE REVIEW

**Comment by jrf0110** [comment]
Do you see any issue with just setting it to `*`?

**Comment by twistedvisions** [comment]
In theory, they could issue a breaking change in 4.x that does screw this up.

In practice, I don't really see that happening - And at any rate, people have to have an explicit version of node-postgres in their own package.json anyway, since this is just a peer, not a dependency, so they would be explicitly choosing to run a version of node-postgres themselves.

**Comment by jrf0110** [comment]
Exactly. Will update package.json shortly

**Comment by twistedvisions** [comment]
thanks!

**Comment by jrf0110** [comment]
Hrmm.. I don't have npm publishing rights on this module.. so, one sec

**Comment by jrf0110** [comment]
Hey, @lalitkapoor - can you add me as a maintainer for this package on npm?

**Comment by twistedvisions** [comment]
Bump - @jrf0110 @lalitkapoor - could you please put this on [npm](https://www.npmjs.org/package/pg-transaction) please.

My travis-ci tests will keep failing until you do!

**Comment by jrf0110** [comment]
Hrm. Sorry about that. I'll try some other contact outlets

**Comment by jrf0110** [comment]
Oh actually, it looks like he added me as a maintainer and didn't tell me! I'll have this in in a minute

**Comment by jrf0110** [comment]
It's in `1.0.3`

**Comment by twistedvisions** [comment]
Beautiful, thanks a bunch!

**Pull request merged**
